name: Publish Android Build

on:
    workflow_dispatch:

jobs:
    publish_release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main
              uses: actions/checkout@v3

            - name: Re-install .NET from Install Scripts and install maui-android Workload
              run: |
                wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
                chmod +x ./dotnet-install.sh
                ./dotnet-install.sh --channel 8.0
                export DOTNET_ROOT=$HOME/.dotnet
                export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
                dotnet workload search
                dotnet workload install maui-android

            - name: Run dotnet publish
              working-directory: Acai/AcaiMobile
              run: |
                dotnet publish -f net8.0-android -c Release
