name: Publish Android Build

on:
    workflow_dispatch:
      inputs:
        releaseVersion:
          description: 'Release / Tag Version (v1.x.x)'
          required: true
          type: string
          default: 'v1.0.0'
        isDraftRelease:
          description: 'Create Release as Draft?'
          required: true
          type: boolean
          default: true
        generateReleaseNotes:
          description: 'Generate Release notes?'
          required: true
          type: boolean
          default: true
          
jobs:
    publish_release:
        runs-on: ubuntu-latest
        
        permissions:
          contents: write
          
        steps:
            - name: Checkout main
              uses: actions/checkout@v3

            - name: Re-install .NET 8 to make .NET MAUI Workloads available
              uses: actions/setup-dotnet@v3
              with: 
                dotnet-version: '8.0.x'

            - name: Install .NET MAUI Workload for Android
              run: dotnet workload install maui-android

            - name: Prepare KeyStore and Password File for Signing
              working-directory: Acai/AcaiMobille
              env:
                KEYSTORE_BASE64: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
                KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
              run: |
                echo "${{ env.KEYSTORE_BASE64 }}" | base64 --decode > acai.keystore

                echo "${{ env.KEYSTORE_PASSWORD }}" > acaiKeyStorePassword

            - name: Run dotnet build and publish on AcaiMobile
              working-directory: Acai/AcaiMobile
              run: |
                dotnet build -t:InstallAndroidDependencies -f net8.0-android -p:AndroidSdkDirectory=\work\android-sdk -p:JavaSdkDirectory=\work\jdk -p:AcceptAndroidSdkLicenses=True
                
                dotnet publish -f net8.0-android -p:AndroidSdkDirectory=\work\android-sdk -p:JavaSdkDirectory=\work\jdk -p:ApplicationVersion=$(echo ${{ inputs.releaseVersion }} | tr -d 'v.') -p:ApplicationDisplayVersion=${{ inputs.releaseVersion }} -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=acai.keystore -p:AndroidSigningKeyAlias=acai -p:AndroidSigningKeyPass=file:acaiKeyStorePassword -p:AndroidSigningStorePass=file:acaiKeyStorePassword -o ./acai_dist
                
                ls acai_dist

            - name: Create new Release and upload APK
              working-directory: Acai/AcaiMobile/acai_dist
              env:
                RUNNER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                created_release_body="$(curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ env.RUNNER_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/not-ed/acai/releases \
                  -d '{"tag_name":"${{ inputs.releaseVersion }}","target_commitish":"main","name":"${{ inputs.releaseVersion }}","draft":${{ inputs.isDraftRelease }},"prerelease":false,"generate_release_notes":${{ inputs.generateReleaseNotes }}}')"
                
                asset_name="com.not_ed.acai-Signed.apk"
                
                asset_url=$(echo $created_release_body | jq .upload_url | sed "s/{.*}/?name=${asset_name}/" | sed 's/"//')
                
                curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ env.RUNNER_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  -H "Content-Type: application/octet-stream" \
                  $asset_url \
                  --data-binary @$asset_name
                
                
