name: Publish Android Build

on:
    workflow_dispatch:
      inputs:
        releaseVersion:
          description: 'Release / Tag Version (1.x.x)'
          required: true
          type: string
          default: 'v1.0.0'
        isDraftRelease:
          description: 'Create Release as Draft?'
          required: true
          type: boolean
          default: true
        


jobs:
    publish_release:
        runs-on: ubuntu-latest
        
        permissions:
          contents: write
          
        steps:
            - name: Checkout main
              uses: actions/checkout@v3

            - name: Setup .NET to provide .NET MAUI Android Workload
              uses: actions/setup-dotnet@v3
              with: 
                dotnet-version: '8.0.x'

            - name: Install .NET MAUI Workload for Android
              run: dotnet workload install maui-android

            - name: Run dotnet build and publish
              working-directory: Acai/AcaiMobile
              run: |
                dotnet build -t:InstallAndroidDependencies -f net8.0-android -p:AndroidSdkDirectory=\work\android-sdk -p:JavaSdkDirectory=\work\jdk -p:AcceptAndroidSdkLicenses=True
                dotnet publish -f net8.0-android -p:AndroidSdkDirectory=\work\android-sdk -p:JavaSdkDirectory=\work\jdk -o ./acai_dist
                ls acai_dist

            - name: Create new Release
              env:
                RUNNER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ env.RUNNER_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/not-ed/acai/releases \
                  -d '{"tag_name":"${{ inputs.releaseVersion }}","target_commitish":"main","name":"${{ inputs.releaseVersion }}","body":"Test release from runner","draft":${{ inputs.isDraftRelease }},"prerelease":false,"generate_release_notes":true}'
