name: Publish Android Build

on:
    workflow_dispatch:
      inputs:
        releaseVersion:
          description: 'Release / Tag Version (1.x.x)'
          required: true
          type: string
          default: 'v1.0.0'
        isDraftRelease:
          description: 'Create Release as Draft?'
          required: true
          type: boolean
          default: true
        


jobs:
    publish_release:
        runs-on: ubuntu-latest
        
        permissions:
          contents: write
          
        steps:
            - name: Checkout main
              uses: actions/checkout@v3



            - name: Create new Release
              working-directory: Acai/AcaiMobile
              env:
                RUNNER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                echo "Test file here" > com.not_ed.acai-Signed.apk
                ls
                created_release_body=$(curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ env.RUNNER_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/not-ed/acai/releases \
                  -d '{"tag_name":"${{ inputs.releaseVersion }}","target_commitish":"main","name":"${{ inputs.releaseVersion }}","body":"Test release from runner","draft":${{ inputs.isDraftRelease }},"prerelease":false,"generate_release_notes":true}')
                asset_name="com.not_ed.acai-Signed.apk"
                asset_url=$(echo $created_release_body | jq .upload_url) | sed "s/{.*}/?name=$asset_name/"
                curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ env.RUNNER_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  -H "Content-Type: application/octet-stream" \
                  $asset_url \
                  --data-binary @./$asset_name
